name: Cypress E2E Pipeline 

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E Tests (Chrome)
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Play Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install-command: npm install
