name: Cypress E2E Pipeline 

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E Tests (Chrome)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 1: Nós instalamos as dependências do jeito "bagunçado" (sem lockfile)
      - name: install
        run: npm install

      # Passo 2: Chamamos o especialista só para rodar (ele traz as libs do Linux)
      - name: Run cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false  # "Não tente instalar, eu já fiz isso acima"
          browser: chrome
          start: npm run cypress:run -- --browser chrome # Força o comando de execução
